name: Security Checks
on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: testing
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          # docker_name: 'owasp/zap2docker-stable'
          target: 'https://sahu04.github.io/website/'
          # rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
