name: Security Checks
on:
  push:
    branches:
      - master

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Permissions
        run: |
          sudo chmod -R 777 ${{ github.workspace }}/zap_reports

      - name: Expose Local Environment
        run: ngrok http 4000  # Adjust port as needed
        background: true

      - name: Wait for ngrok to Start
        run: sleep 5

      - name: Run ZAP Baseline Scan
        run: |
          /usr/bin/docker run -v ${{ github.workspace }}/zap_reports:/zap/wrk/:rw --network=host -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://host.docker.internal:4040 -J /zap/wrk/report_json.json -w /zap/wrk/report_md.md -r /zap/wrk/report_html.html
